### PR TITLE
Switch to bibtex

### PR DESCRIPTION
**Pull request by timj**
This is not ready to merge yet.

I have added bibkeys to every bibitem and switched all the text to use simple `\cite`. There are some missing or ambiguous references that I need to ask people about. I'll use this PR to ask questions if I can't work it out.

@ivezic @michaelstrauss and others, please don't edit the v4-dev branch until I've merged this in since I've changed almost every line (more than 300 reference mentions in the text).

### CODE REVIEW

**Comment by timj** [comment]
My work on the references has indicated that we have a number of missing references and some ambiguous references where "Author et al (YYYY)" maps to multiple reference entries.

@ivezic or others can you please help resolve the following.

Ambiguous references:

* Abbott2017
* Scovacricchi2017
* Weinberg2013

Missing references:

* Cai et al 2013
* Campanelli et al 2011
* Colin et al 2011
* Della Valle & Livio 1995 (https://ui.adsabs.harvard.edu/#abs/1995ApJ...452..704D/abstract ?)
* Gordon et al 2007
* Javanmardi et al 2015 (https://ui.adsabs.harvard.edu/#abs/2015ApJ...810...47J/abstract ?)
* Reiss et al 1999 (is that meant to be Riess et al 1998?)
* Reyes et al 2007
* Scovacricchi et al 2015 (no 2015 paper exists. 2016 or 2017?)

Questionable

* Is Macaulay2016 meant to be Macaulay2017?
* Is Rocha2012 meant to be Rocha2013?

**Comment by timj** [comment]
Is Trilling2017 meant to be http://iopscience.iop.org/article/10.3847/2041-8213/aa9989/pdf ?

**Comment by timj** [comment]
Looking at git blame. I think the following people added the ambiguous/missing references:

* Abbott2017: @rmandelb (?)
* Scovacricchi2015: @fedhere 
* Scovaricchi2016/2017 (wrong spelling): @rbiswas4
* Weinberg2013: @ivezic 
* Cai2013: @rbiswas4
* Campanelli2011: @rbiswas4
* Colin2011: @rbiswas4
* DellaValle1995: @fedhere 
* Gordon2007: @rbiswas4
* Javanmardi2015: @rbiswas4
* Reiss1999: @rbiswas4
* Reyes2007: @ivezic 
* Macaulay2016: @rbiswas4
* Rocha2013: Anthony Dawson

So @rbiswas4 is the clear winner.

**Comment by rmandelb** [comment]
The Abbott et al 2017 should be 2017a.

**Comment by timj** [comment]
The initial usage of bibtex is now complete. I'd like to sort out the missing references before merging if at all possible. Next step for me is to use `\citep` and `\citet` where appropriate.

Reminder that current missing list:
```
Warning--I didn't find a database entry for "Weinberg2013"
Warning--I didn't find a database entry for "Rocha2012"
Warning--I didn't find a database entry for "DES"
Warning--I didn't find a database entry for "Tyson2008b"
Warning--I didn't find a database entry for "Reyes2007"
Warning--I didn't find a database entry for "Gordon2007"
Warning--I didn't find a database entry for "Macaulay2016"
Warning--I didn't find a database entry for "Scovacricchi2017"
Warning--I didn't find a database entry for "Reiss1999"
Warning--I didn't find a database entry for "Javanmardi2015"
Warning--I didn't find a database entry for "Campanelli2011"
Warning--I didn't find a database entry for "Cai2013"
Warning--I didn't find a database entry for "Colin2011"
Warning--I didn't find a database entry for "DellaValle1995"
Warning--I didn't find a database entry for "Scovacricchi2015"
Warning--I didn't find a database entry for "Abbott2017"
```

**Comment by rmandelb** [comment]
Something must've gotten munged somewhere, because at least a few of these were in the tex file when I last dealt with it.  For example, Weinberg2013 was this:
```
\bibitem[()]{} Weinberg, D.H., Mortonson, M.J., Eisenstein, D.J.,
  Hirata, C., Riess, A.G., \& Rozo, E. 2013, Physics Reports, 530, 87
```

**Comment by timj** [comment]
I mentioned the Weinberg2013 not because it wasn't in the file but because there were two entries for 2013 and I didn't know which. I'll fix that and the Abbott.

**Comment by rbiswas4** [comment]
@timj I was quite confused about what convention was being followed. I would be happy to fix things to whatever convention is being followed: for example
- Is using the ads bibtex entry fine for the purpose?
- Is using the ads key fine for the purpose. (clearly the references I made in the text itself won't match the ads keys, and I can fix that.)

**Comment by timj** [comment]
@rmandelb are both of the Abbott2017 entries the same?

**Comment by timj** [comment]
@rbiswas4 tell me the bibcodes and I'll take it from there. I've been reworking the whole paper to use bibcodes and ADS bibtex and I'm almost done so rather than confuse things please tell me the bibcodes.

**Comment by timj** [comment]
@rmandelb sorry for the continued message, but are both the Weinberg2013 references the same? There is one in science.tex and one in system.tex.

**Comment by timj** [comment]
@ivezic I'm now done with switching things to use bibtex. It's probably okay to merge this even without resolving the ~ 10 outstanding references questions since this is a huge amount of work to redo if people start committing work again and I want to minimize the time this PR is hanging around. It's obvious now which references need fixing because bibtex tells you.

**Comment by rmandelb** [comment]
> are both of the Abbott2017 entries the same?

There are two Abbott2017 entries in the bibliography, one of which says 2017a and one of which says 2017b in the year.  The previous text had referred to these directly as 2017a and 2017b by year.  Then there were two places in the text that referred just to Abbott et al (2017), so what I meant above is that *both* of those should 2017a.  Was that what you meant?

**Comment by rmandelb** [comment]
> are both the Weinberg2013 references the same? 

I see what you mean now.  The one in science.tex is the one I put above (second author Mortonson).  In system.tex, there is another Weinberg et al 2013 in a discussion of dark matter on subgalactic scales.  That one is the Weinberg+13 reference with second author Bullock.

**Comment by rmandelb** [comment]
As for the Reyes+07 reference: that's just wrong, it should be the same Reyes+10 that's already referred to elsewhere in the paper.

**Comment by rbiswas4** [comment]
@timj  Here are the names-> bibcode matching you asked for:

Javanmardi2015 2015ApJ...810...47J
Reiss1999 2000ASPC..201...80R
Macaulay2016 2017MNRAS.467..259M
Scovaricchi2016/2017 2017MNRAS.465.2862S
Colin2011 2011MNRAS.414..264C
Gordon2007 2007PhRvL..99h1301G

**Comment by timj** [comment]
@rmandelb Thanks. Please can you check 2105168c25d1d51d17056e7468dc4ad8a0a25d9c ?
@rbiswas4 Thanks. Please can you check 5af160174909a76e52114bb583e6721b1e31a5c3 ?

Also, @rbiswas4 can you confirm that Scovaricchi2015 doesn't exist and it's really meant to be the 2017 paper? Do you not know the Campanelli and Cai ones?

@RobertLuptonTheGood which reference did you want to use for DES? In commit d1a91f10b9488840e9f2530756ba565344d48987 you left it empty.

The missing list is now:

Warning--I didn't find a database entry for "Rocha2012"
Warning--I didn't find a database entry for "DES"
Warning--I didn't find a database entry for "Campanelli2011"
Warning--I didn't find a database entry for "Cai2013"
Warning--I didn't find a database entry for "DellaValle1995"
Warning--I didn't find a database entry for "Scovacricchi2015"

**Comment by rbiswas4** [comment]
@timj 
> Also, @rbiswas4 can you confirm that Scovaricchi2015 doesn't exist and it's really meant to be the 2017 paper? 
Scovaricchi2015 : 2016MNRAS.456.1700S (that is from @fedhere but is easy to be confident about)
Scovaricchi2016/2017 2017MNRAS.465.2862S
(The confusion of 2015/2016 stems from arxiv post years vs published years, which was why I wrote the other paper is 2016/2017)

> Do you not know the Campanelli and Cai ones?
The others that I missed (sorry!)
Cai2013 2013PhRvD..87l3522C
Campanelli2011 2011PhRvD..83j3503C

Finally, reviewing  commit 5af1601, I notice that the isotropy references \citep{2015ApJ...810...47J,2010JCAP...12..012A,Campanelli2011,Cai2013,2011MNRAS.414..264C} are in the wrong order of publication dates with reference to the rest of the cases in this section because I wrote it incorrectly. So, I suggest that this be changed to:
\citep{2010JCAP...12..012A,2011MNRAS.414..264C,2011PhRvD..83j3503C,2013PhRvD..87l3522C,2015ApJ...810...47J} (with correct bibtex codes inserted for the two missing ones).

**Comment by rmandelb** [comment]
> @rmandelb Thanks. Please can you check 2105168 ?

It's good, thanks.

**Comment by timj** [comment]
Thanks everyone. Only two left now. I need @RobertLuptonTheGood to choose his DES reference and @fedhere to confirm that DellaValle1995 is 1995ApJ...452..704D

**Comment by timj** [comment]
Also, there is a reference to `Fig:bao` but that figure was commented out by @rmandelb. Shall I remove the call out to `Fig:bao` from the text?

**Comment by michaelstrauss** [comment]
> On Dec 8, 2017, at 9:03 AM, Tim Jenness <notifications@github.com> wrote:
> 
> Also, there is a reference to Fig:bao but that figure was commented out by @rmandelb. Shall I remove the call out to Fig:bao from the text?
Yes.

**Comment by timj** [comment]
I think I'm done. All references are fixed and no warnings from bibtex. @ivezic or @michaelstrauss do you want to take a look or shall I merge it now?

**Comment by timj** [comment]
@michaelstrauss reports:

> as far as I am concerned, I am happy for you to merge.

**Pull request merged**
