### PR TITLE
Switch to AASTeX 6.1

### PR DESCRIPTION
**Pull request by timj**
* Change author format
* Use deluxetables
* Fix bounding boxes of figures to make them fit properly
* Refer to tables using `\ref`

### CODE REVIEW

**Comment by timj** [comment]
@ivezic AASTeX6.1 handles large author lists much better. If this PR is okay with you we can merge it and I can start to tackle the bigger technical problems with the paper.

**Comment by ivezic** [comment]
Great, thanks!

**Comment by ivezic** [comment]
Tim, I am surprised it went to 55 pages (from ~44 or so) just because of style change...
But more importantly, the author list is truncated with "et al." after Kalirai - do you 
understand why (and is it configurable)?

**Comment by timj** [comment]
Regarding the author list, I believe it's because AAS journals have a limit of 40 authors on the front page. There is a macro for listing all the authors at the end (although I haven't quite sorted it out yet).

I'm working on the bibtex at the moment.

**Pull request merged**
