### PR TITLE
LSST DESC input to 2017 update

### PR DESCRIPTION
**Pull request by drphilmarshall**
Hi @ivezic ,

I'm opening a PR to track our proposed changes to section .1.1 and 4.1 of the LSST overview paper, due Nov 15. Let me know if you want this re-directed at some other branch - and feel free to give us feedback here in this thread

Phil & the LSST DESC

### CODE REVIEW

**Comment by ivezic** [comment]
Phil,
there are lots of conflicts and I am not sure that everything is kosher. For example,
the proposed merge would remove the first seven bullets in Section 4.3 (Exploring 
the Transient Optical Sky). Can you please take a look?

**Comment by drphilmarshall** [comment]
Something odd going on here - I resolved the conflicts via the web interface, but they are persisting. I'll update the DESC branch locally and see if that fixes things. (It should.)

**Comment by drphilmarshall** [comment]
OK @ivezic , conflicts fixed. I also pushed a minimal edit to the Dark Energy & Dark Matter sections in our branch. How is our deadline looking? If there's any extension time I'll try to make further improvements.

**Comment by ivezic** [comment]
Yes, @drphilmarshall a few more days is not too long to wait (I got other edits to work on) 
for further improvements!

**Comment by timj** [comment]
and at some point I have to work on the author list...

**Comment by drphilmarshall** [comment]
Actually, since you mention it - presumably anyone who makes a substantive
improvement to this paper would qualify to be added to the author list?
Thinking about what I can offer to the DESC working group leads in return
for their help...

**Comment by ivezic** [comment]
Yes, we'd definitely add as coauthors all those who made substantive
improvements!

**Pull request merged**
